### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by alexsohn1126** [shivankgoel003/DataBreach_Ransomware_Stats#1]
- Repo name and the paper seems to be on different topics. I assumed this paper was going to be about data breaches from the title, but it is actually about air pollution and mortality rates.
- Final_paper.Rproj file shows this is a school project, please rename it
- Use Parquet files instead of csv for your cleaned data
- Good job on sketches
- Awesome 05-model.R, but maybe change the date and contact info?
- Add other prerequisites in test_data.R, such as downloading the data and cleaning it using the previous R scripts
- download_data.R doesn't seem to be doing anything currently
- The code seems to be about data breaches, but the paper mentions both data breaches and air quality, I'm sure you'll fix this later, but just pointing it out!
- usage.txt seems to be the same thing as the starter folder's usage.txt, make sure to change it before final submission!

**Comment by shivankgoel003** [comment]
Thanks for your valuable feedback. The suggestions were helpful and all issues have been fixed
