### ISSUE TITLE
Peer Review By Vanshika Vanshika

### ISSUE THREAD

**Issue by vanshikav2** [shivankgoel003/DataBreach_Ransomware_Stats#2]
Your README is wrong and is some other paper you did. All the information on the README does not represent your recent paper.

Your paper folder needs to be cleaned of the files you won't be using. Your paper contains only graphs of your dataset. The analysis and all the information in the paper is about another paper about mortality rates. The graphs' code is also being displayed on the paper which should not be the case.

Good job with the scripts. All the simulation, cleaning, model and testing of the data is done properly and in detail. You need to delete the unnecessary files like replications and download scripts.

Your other folder is unfinished and needs to be completed.

The data folder contains your raw data file and your cleaned one as well.

Good job with the starting phase of the paper but a lot of things need to be completed.

**Comment by shivankgoel003** [comment]
Thanks Vanshika for your feedback, all the issues have been fixed.
