### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by faralk** [shivankgoel003/DataBreach_Ransomware_Stats#3]
**Introduction**

- When you are telegraphing the structure of your paper, make sure to use cross-references
- Avoid informal language such as "cybersecurity is _super_ important"

**Data** 

- In **2.1 - Data Source and Collection**, I would try to use headings to separate the three datasets you used to increase readability 
- In **2.3 - Data Modification**, I would remove any code in that section. Code should not appear in the paper.

### Other Feedback
**data**

- It is more ideal to use parquet files for everything, but at the very minimum, the Dataset-cyberattacks-06102020.xlsx file should definitely be changed to a csv or ideally, a parquet file.

**other/literature**

- Please do not forget to remove the paper in folder.

Otherwise, nice work so far!

**Comment by shivankgoel003** [comment]
Thanks Fares, for taking time to review! I tried considering all your suggestions and fixing the issuess.
